package com.homw.gateway.entity;

import java.io.Serializable;

public class DeviceInfo implements Serializable {
	
	private static final long serialVersionUID = -4908765150502415252L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.DEVICE_ID
     *
     * @mbggenerated
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.DEVICE_TYPE
     *
     * @mbggenerated
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.OUTER_NO
     *
     * @mbggenerated
     */
    private String outerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.DOOR_IP
     *
     * @mbggenerated
     */
    private String doorIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.DOOR_PORT
     *
     * @mbggenerated
     */
    private Integer doorPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.DOOR_ADDR
     *
     * @mbggenerated
     */
    private String doorAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.DOOR_READNO
     *
     * @mbggenerated
     */
    private Integer doorReadno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.DOOR_NAME
     *
     * @mbggenerated
     */
    private String doorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.ELEC_ADDR
     *
     * @mbggenerated
     */
    private String elecAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.ELEC_STATUS
     *
     * @mbggenerated
     */
    private String elecStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.ELEC_USE_POINT
     *
     * @mbggenerated
     */
    private Integer elecUsePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.ELEC_LEFT_POINT
     *
     * @mbggenerated
     */
    private Integer elecLeftPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.CREATE_USER_ID
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.CREATE_USER_TYPE
     *
     * @mbggenerated
     */
    private String createUserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.UPDATE_USER_TYPE
     *
     * @mbggenerated
     */
    private String updateUserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.REFER_ELEC_ID
     *
     * @mbggenerated
     */
    private Long referElecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.IS_REFER_NODE
     *
     * @mbggenerated
     */
    private Boolean isReferNode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.RATE
     *
     * @mbggenerated
     */
    private Integer rate;
    
    private Integer faceDeviceId;
    public Integer getFaceDeviceId() {
		return faceDeviceId;
	}

	public void setFaceDeviceId(Integer faceDeviceId) {
		this.faceDeviceId = faceDeviceId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.DEVICE_ID
     *
     * @return the value of device_info.DEVICE_ID
     *
     * @mbggenerated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.DEVICE_ID
     *
     * @param deviceId the value for device_info.DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.DEVICE_TYPE
     *
     * @return the value of device_info.DEVICE_TYPE
     *
     * @mbggenerated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.DEVICE_TYPE
     *
     * @param deviceType the value for device_info.DEVICE_TYPE
     *
     * @mbggenerated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.OUTER_NO
     *
     * @return the value of device_info.OUTER_NO
     *
     * @mbggenerated
     */
    public String getOuterNo() {
        return outerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.OUTER_NO
     *
     * @param outerNo the value for device_info.OUTER_NO
     *
     * @mbggenerated
     */
    public void setOuterNo(String outerNo) {
        this.outerNo = outerNo == null ? null : outerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.DOOR_IP
     *
     * @return the value of device_info.DOOR_IP
     *
     * @mbggenerated
     */
    public String getDoorIp() {
        return doorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.DOOR_IP
     *
     * @param doorIp the value for device_info.DOOR_IP
     *
     * @mbggenerated
     */
    public void setDoorIp(String doorIp) {
        this.doorIp = doorIp == null ? null : doorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.DOOR_PORT
     *
     * @return the value of device_info.DOOR_PORT
     *
     * @mbggenerated
     */
    public Integer getDoorPort() {
        return doorPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.DOOR_PORT
     *
     * @param doorPort the value for device_info.DOOR_PORT
     *
     * @mbggenerated
     */
    public void setDoorPort(Integer doorPort) {
        this.doorPort = doorPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.DOOR_ADDR
     *
     * @return the value of device_info.DOOR_ADDR
     *
     * @mbggenerated
     */
    public String getDoorAddr() {
        return doorAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.DOOR_ADDR
     *
     * @param doorAddr the value for device_info.DOOR_ADDR
     *
     * @mbggenerated
     */
    public void setDoorAddr(String doorAddr) {
        this.doorAddr = doorAddr == null ? null : doorAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.DOOR_READNO
     *
     * @return the value of device_info.DOOR_READNO
     *
     * @mbggenerated
     */
    public Integer getDoorReadno() {
        return doorReadno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.DOOR_READNO
     *
     * @param doorReadno the value for device_info.DOOR_READNO
     *
     * @mbggenerated
     */
    public void setDoorReadno(Integer doorReadno) {
        this.doorReadno = doorReadno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.DOOR_NAME
     *
     * @return the value of device_info.DOOR_NAME
     *
     * @mbggenerated
     */
    public String getDoorName() {
        return doorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.DOOR_NAME
     *
     * @param doorName the value for device_info.DOOR_NAME
     *
     * @mbggenerated
     */
    public void setDoorName(String doorName) {
        this.doorName = doorName == null ? null : doorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.ELEC_ADDR
     *
     * @return the value of device_info.ELEC_ADDR
     *
     * @mbggenerated
     */
    public String getElecAddr() {
        return elecAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.ELEC_ADDR
     *
     * @param elecAddr the value for device_info.ELEC_ADDR
     *
     * @mbggenerated
     */
    public void setElecAddr(String elecAddr) {
        this.elecAddr = elecAddr == null ? null : elecAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.ELEC_STATUS
     *
     * @return the value of device_info.ELEC_STATUS
     *
     * @mbggenerated
     */
    public String getElecStatus() {
        return elecStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.ELEC_STATUS
     *
     * @param elecStatus the value for device_info.ELEC_STATUS
     *
     * @mbggenerated
     */
    public void setElecStatus(String elecStatus) {
        this.elecStatus = elecStatus == null ? null : elecStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.ELEC_USE_POINT
     *
     * @return the value of device_info.ELEC_USE_POINT
     *
     * @mbggenerated
     */
    public Integer getElecUsePoint() {
        return elecUsePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.ELEC_USE_POINT
     *
     * @param elecUsePoint the value for device_info.ELEC_USE_POINT
     *
     * @mbggenerated
     */
    public void setElecUsePoint(Integer elecUsePoint) {
        this.elecUsePoint = elecUsePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.ELEC_LEFT_POINT
     *
     * @return the value of device_info.ELEC_LEFT_POINT
     *
     * @mbggenerated
     */
    public Integer getElecLeftPoint() {
        return elecLeftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.ELEC_LEFT_POINT
     *
     * @param elecLeftPoint the value for device_info.ELEC_LEFT_POINT
     *
     * @mbggenerated
     */
    public void setElecLeftPoint(Integer elecLeftPoint) {
        this.elecLeftPoint = elecLeftPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.STATUS
     *
     * @return the value of device_info.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.STATUS
     *
     * @param status the value for device_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.VERSION
     *
     * @return the value of device_info.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.VERSION
     *
     * @param version the value for device_info.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.CREATE_USER_ID
     *
     * @return the value of device_info.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.CREATE_USER_ID
     *
     * @param createUserId the value for device_info.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.CREATE_TIME
     *
     * @return the value of device_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.CREATE_TIME
     *
     * @param createTime the value for device_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.CREATE_USER_TYPE
     *
     * @return the value of device_info.CREATE_USER_TYPE
     *
     * @mbggenerated
     */
    public String getCreateUserType() {
        return createUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.CREATE_USER_TYPE
     *
     * @param createUserType the value for device_info.CREATE_USER_TYPE
     *
     * @mbggenerated
     */
    public void setCreateUserType(String createUserType) {
        this.createUserType = createUserType == null ? null : createUserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.UPDATE_USER_ID
     *
     * @return the value of device_info.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.UPDATE_USER_ID
     *
     * @param updateUserId the value for device_info.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.UPDATE_TIME
     *
     * @return the value of device_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.UPDATE_TIME
     *
     * @param updateTime the value for device_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.UPDATE_USER_TYPE
     *
     * @return the value of device_info.UPDATE_USER_TYPE
     *
     * @mbggenerated
     */
    public String getUpdateUserType() {
        return updateUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.UPDATE_USER_TYPE
     *
     * @param updateUserType the value for device_info.UPDATE_USER_TYPE
     *
     * @mbggenerated
     */
    public void setUpdateUserType(String updateUserType) {
        this.updateUserType = updateUserType == null ? null : updateUserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.REFER_ELEC_ID
     *
     * @return the value of device_info.REFER_ELEC_ID
     *
     * @mbggenerated
     */
    public Long getReferElecId() {
        return referElecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.REFER_ELEC_ID
     *
     * @param referElecId the value for device_info.REFER_ELEC_ID
     *
     * @mbggenerated
     */
    public void setReferElecId(Long referElecId) {
        this.referElecId = referElecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.IS_REFER_NODE
     *
     * @return the value of device_info.IS_REFER_NODE
     *
     * @mbggenerated
     */
    public Boolean getIsReferNode() {
        return isReferNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.IS_REFER_NODE
     *
     * @param isReferNode the value for device_info.IS_REFER_NODE
     *
     * @mbggenerated
     */
    public void setIsReferNode(Boolean isReferNode) {
        this.isReferNode = isReferNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.RATE
     *
     * @return the value of device_info.RATE
     *
     * @mbggenerated
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.RATE
     *
     * @param rate the value for device_info.RATE
     *
     * @mbggenerated
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }
}