package com.homw.gateway.entity;

public class DeviceElectricUseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.DEVICE_USE_INFO_ID
     *
     * @mbggenerated
     */
    private Long deviceUseInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.OUTER_NO
     *
     * @mbggenerated
     */
    private String outerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.ELEC_ADDR
     *
     * @mbggenerated
     */
    private String elecAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.YESDAY
     *
     * @mbggenerated
     */
    private String yesday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.NOWDAY
     *
     * @mbggenerated
     */
    private String nowday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.YESDAY_POINT
     *
     * @mbggenerated
     */
    private Integer yesdayPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.NOWDAY_POINT
     *
     * @mbggenerated
     */
    private Integer nowdayPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.CUR_USE_POINT
     *
     * @mbggenerated
     */
    private Integer curUsePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.OTHER_USE_POINT
     *
     * @mbggenerated
     */
    private Integer otherUsePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.REFER_ELEC_ID
     *
     * @mbggenerated
     */
    private Long referElecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_electric_use_info.DEVICE_ID
     *
     * @mbggenerated
     */
    private Long deviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.DEVICE_USE_INFO_ID
     *
     * @return the value of device_electric_use_info.DEVICE_USE_INFO_ID
     *
     * @mbggenerated
     */
    public Long getDeviceUseInfoId() {
        return deviceUseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.DEVICE_USE_INFO_ID
     *
     * @param deviceUseInfoId the value for device_electric_use_info.DEVICE_USE_INFO_ID
     *
     * @mbggenerated
     */
    public void setDeviceUseInfoId(Long deviceUseInfoId) {
        this.deviceUseInfoId = deviceUseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.OUTER_NO
     *
     * @return the value of device_electric_use_info.OUTER_NO
     *
     * @mbggenerated
     */
    public String getOuterNo() {
        return outerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.OUTER_NO
     *
     * @param outerNo the value for device_electric_use_info.OUTER_NO
     *
     * @mbggenerated
     */
    public void setOuterNo(String outerNo) {
        this.outerNo = outerNo == null ? null : outerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.ELEC_ADDR
     *
     * @return the value of device_electric_use_info.ELEC_ADDR
     *
     * @mbggenerated
     */
    public String getElecAddr() {
        return elecAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.ELEC_ADDR
     *
     * @param elecAddr the value for device_electric_use_info.ELEC_ADDR
     *
     * @mbggenerated
     */
    public void setElecAddr(String elecAddr) {
        this.elecAddr = elecAddr == null ? null : elecAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.YESDAY
     *
     * @return the value of device_electric_use_info.YESDAY
     *
     * @mbggenerated
     */
    public String getYesday() {
        return yesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.YESDAY
     *
     * @param yesday the value for device_electric_use_info.YESDAY
     *
     * @mbggenerated
     */
    public void setYesday(String yesday) {
        this.yesday = yesday == null ? null : yesday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.NOWDAY
     *
     * @return the value of device_electric_use_info.NOWDAY
     *
     * @mbggenerated
     */
    public String getNowday() {
        return nowday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.NOWDAY
     *
     * @param nowday the value for device_electric_use_info.NOWDAY
     *
     * @mbggenerated
     */
    public void setNowday(String nowday) {
        this.nowday = nowday == null ? null : nowday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.YESDAY_POINT
     *
     * @return the value of device_electric_use_info.YESDAY_POINT
     *
     * @mbggenerated
     */
    public Integer getYesdayPoint() {
        return yesdayPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.YESDAY_POINT
     *
     * @param yesdayPoint the value for device_electric_use_info.YESDAY_POINT
     *
     * @mbggenerated
     */
    public void setYesdayPoint(Integer yesdayPoint) {
        this.yesdayPoint = yesdayPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.NOWDAY_POINT
     *
     * @return the value of device_electric_use_info.NOWDAY_POINT
     *
     * @mbggenerated
     */
    public Integer getNowdayPoint() {
        return nowdayPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.NOWDAY_POINT
     *
     * @param nowdayPoint the value for device_electric_use_info.NOWDAY_POINT
     *
     * @mbggenerated
     */
    public void setNowdayPoint(Integer nowdayPoint) {
        this.nowdayPoint = nowdayPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.CUR_USE_POINT
     *
     * @return the value of device_electric_use_info.CUR_USE_POINT
     *
     * @mbggenerated
     */
    public Integer getCurUsePoint() {
        return curUsePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.CUR_USE_POINT
     *
     * @param curUsePoint the value for device_electric_use_info.CUR_USE_POINT
     *
     * @mbggenerated
     */
    public void setCurUsePoint(Integer curUsePoint) {
        this.curUsePoint = curUsePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.OTHER_USE_POINT
     *
     * @return the value of device_electric_use_info.OTHER_USE_POINT
     *
     * @mbggenerated
     */
    public Integer getOtherUsePoint() {
        return otherUsePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.OTHER_USE_POINT
     *
     * @param otherUsePoint the value for device_electric_use_info.OTHER_USE_POINT
     *
     * @mbggenerated
     */
    public void setOtherUsePoint(Integer otherUsePoint) {
        this.otherUsePoint = otherUsePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.STATUS
     *
     * @return the value of device_electric_use_info.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.STATUS
     *
     * @param status the value for device_electric_use_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.VERSION
     *
     * @return the value of device_electric_use_info.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.VERSION
     *
     * @param version the value for device_electric_use_info.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.CREATE_TIME
     *
     * @return the value of device_electric_use_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.CREATE_TIME
     *
     * @param createTime the value for device_electric_use_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.UPDATE_TIME
     *
     * @return the value of device_electric_use_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.UPDATE_TIME
     *
     * @param updateTime the value for device_electric_use_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.REFER_ELEC_ID
     *
     * @return the value of device_electric_use_info.REFER_ELEC_ID
     *
     * @mbggenerated
     */
    public Long getReferElecId() {
        return referElecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.REFER_ELEC_ID
     *
     * @param referElecId the value for device_electric_use_info.REFER_ELEC_ID
     *
     * @mbggenerated
     */
    public void setReferElecId(Long referElecId) {
        this.referElecId = referElecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_electric_use_info.DEVICE_ID
     *
     * @return the value of device_electric_use_info.DEVICE_ID
     *
     * @mbggenerated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_electric_use_info.DEVICE_ID
     *
     * @param deviceId the value for device_electric_use_info.DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }
}