package com.homw.gateway.entity;

import java.util.Date;

public class DeviceCommandLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.LOG_ID
     *
     * @mbggenerated
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.USER_TYPE
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.USER_MOBILE
     *
     * @mbggenerated
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.OUTER_NO
     *
     * @mbggenerated
     */
    private String outerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.DOOR_NAME
     *
     * @mbggenerated
     */
    private String doorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.DEVICE_TYPE
     *
     * @mbggenerated
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_command_log.CAST_TIME
     *
     * @mbggenerated
     */
    private Long castTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.LOG_ID
     *
     * @return the value of device_command_log.LOG_ID
     *
     * @mbggenerated
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.LOG_ID
     *
     * @param logId the value for device_command_log.LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.USER_ID
     *
     * @return the value of device_command_log.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.USER_ID
     *
     * @param userId the value for device_command_log.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.USER_TYPE
     *
     * @return the value of device_command_log.USER_TYPE
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.USER_TYPE
     *
     * @param userType the value for device_command_log.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.USER_NAME
     *
     * @return the value of device_command_log.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.USER_NAME
     *
     * @param userName the value for device_command_log.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.USER_MOBILE
     *
     * @return the value of device_command_log.USER_MOBILE
     *
     * @mbggenerated
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.USER_MOBILE
     *
     * @param userMobile the value for device_command_log.USER_MOBILE
     *
     * @mbggenerated
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.OUTER_NO
     *
     * @return the value of device_command_log.OUTER_NO
     *
     * @mbggenerated
     */
    public String getOuterNo() {
        return outerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.OUTER_NO
     *
     * @param outerNo the value for device_command_log.OUTER_NO
     *
     * @mbggenerated
     */
    public void setOuterNo(String outerNo) {
        this.outerNo = outerNo == null ? null : outerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.DOOR_NAME
     *
     * @return the value of device_command_log.DOOR_NAME
     *
     * @mbggenerated
     */
    public String getDoorName() {
        return doorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.DOOR_NAME
     *
     * @param doorName the value for device_command_log.DOOR_NAME
     *
     * @mbggenerated
     */
    public void setDoorName(String doorName) {
        this.doorName = doorName == null ? null : doorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.DEVICE_TYPE
     *
     * @return the value of device_command_log.DEVICE_TYPE
     *
     * @mbggenerated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.DEVICE_TYPE
     *
     * @param deviceType the value for device_command_log.DEVICE_TYPE
     *
     * @mbggenerated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.CREATE_TIME
     *
     * @return the value of device_command_log.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.CREATE_TIME
     *
     * @param createTime the value for device_command_log.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_command_log.CAST_TIME
     *
     * @return the value of device_command_log.CAST_TIME
     *
     * @mbggenerated
     */
    public Long getCastTime() {
        return castTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_command_log.CAST_TIME
     *
     * @param castTime the value for device_command_log.CAST_TIME
     *
     * @mbggenerated
     */
    public void setCastTime(Long castTime) {
        this.castTime = castTime;
    }
}