package com.homw.gateway.entity;

public class Sign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.SIGN_ID
     *
     * @mbggenerated
     */
    private Long signId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.APP_KEY
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.APP_VALUE
     *
     * @mbggenerated
     */
    private String appValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.APP_TYPE
     *
     * @mbggenerated
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.CREATE_USER_ID
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.CREATE_TIME
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.CREATE_USER_TYPE
     *
     * @mbggenerated
     */
    private String createUserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_sign.UPDATE_USER_TYPE
     *
     * @mbggenerated
     */
    private String updateUserType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.SIGN_ID
     *
     * @return the value of device_sign.SIGN_ID
     *
     * @mbggenerated
     */
    public Long getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.SIGN_ID
     *
     * @param signId the value for device_sign.SIGN_ID
     *
     * @mbggenerated
     */
    public void setSignId(Long signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.APP_KEY
     *
     * @return the value of device_sign.APP_KEY
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.APP_KEY
     *
     * @param appKey the value for device_sign.APP_KEY
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.APP_VALUE
     *
     * @return the value of device_sign.APP_VALUE
     *
     * @mbggenerated
     */
    public String getAppValue() {
        return appValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.APP_VALUE
     *
     * @param appValue the value for device_sign.APP_VALUE
     *
     * @mbggenerated
     */
    public void setAppValue(String appValue) {
        this.appValue = appValue == null ? null : appValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.APP_TYPE
     *
     * @return the value of device_sign.APP_TYPE
     *
     * @mbggenerated
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.APP_TYPE
     *
     * @param appType the value for device_sign.APP_TYPE
     *
     * @mbggenerated
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.STATUS
     *
     * @return the value of device_sign.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.STATUS
     *
     * @param status the value for device_sign.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.VERSION
     *
     * @return the value of device_sign.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.VERSION
     *
     * @param version the value for device_sign.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.CREATE_USER_ID
     *
     * @return the value of device_sign.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.CREATE_USER_ID
     *
     * @param createUserId the value for device_sign.CREATE_USER_ID
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.CREATE_TIME
     *
     * @return the value of device_sign.CREATE_TIME
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.CREATE_TIME
     *
     * @param createTime the value for device_sign.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.CREATE_USER_TYPE
     *
     * @return the value of device_sign.CREATE_USER_TYPE
     *
     * @mbggenerated
     */
    public String getCreateUserType() {
        return createUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.CREATE_USER_TYPE
     *
     * @param createUserType the value for device_sign.CREATE_USER_TYPE
     *
     * @mbggenerated
     */
    public void setCreateUserType(String createUserType) {
        this.createUserType = createUserType == null ? null : createUserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.UPDATE_USER_ID
     *
     * @return the value of device_sign.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.UPDATE_USER_ID
     *
     * @param updateUserId the value for device_sign.UPDATE_USER_ID
     *
     * @mbggenerated
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.UPDATE_TIME
     *
     * @return the value of device_sign.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.UPDATE_TIME
     *
     * @param updateTime the value for device_sign.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_sign.UPDATE_USER_TYPE
     *
     * @return the value of device_sign.UPDATE_USER_TYPE
     *
     * @mbggenerated
     */
    public String getUpdateUserType() {
        return updateUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_sign.UPDATE_USER_TYPE
     *
     * @param updateUserType the value for device_sign.UPDATE_USER_TYPE
     *
     * @mbggenerated
     */
    public void setUpdateUserType(String updateUserType) {
        this.updateUserType = updateUserType == null ? null : updateUserType.trim();
    }
}