package com.homw.gateway.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.homw.gateway.entity.DeviceCommandLog;
import com.homw.gateway.entity.example.DeviceCommandLogExample;

public interface DeviceCommandLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int countByExample(DeviceCommandLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceCommandLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int insert(DeviceCommandLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int insertSelective(DeviceCommandLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    List<DeviceCommandLog> selectByExample(DeviceCommandLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    DeviceCommandLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceCommandLog record, @Param("example") DeviceCommandLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceCommandLog record, @Param("example") DeviceCommandLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceCommandLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceCommandLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    List<Long> selectIdsByExample(DeviceCommandLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_command_log
     *
     * @mbggenerated
     */
    Integer batchInsert(List<DeviceCommandLog> records);
}