package com.homw.gateway.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.homw.gateway.entity.DeviceUser;
import com.homw.gateway.entity.example.DeviceUserExample;

public interface DeviceUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int countByExample(DeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int insert(DeviceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int insertSelective(DeviceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    List<DeviceUser> selectByExample(DeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    DeviceUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceUser record, @Param("example") DeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceUser record, @Param("example") DeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    List<Long> selectIdsByExample(DeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_user
     *
     * @mbggenerated
     */
    Integer batchInsert(List<DeviceUser> records);
}