package com.homw.gateway.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.homw.gateway.entity.DeviceInfo;
import com.homw.gateway.entity.example.DeviceInfoExample;

public interface DeviceInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int countByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int insert(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    List<DeviceInfo> selectByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    DeviceInfo selectByPrimaryKey(Long deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceInfo record, @Param("example") DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceInfo record, @Param("example") DeviceInfoExample example);
    
    int updateDeviceStatus(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    List<Long> selectIdsByExample(DeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    Integer batchInsert(List<DeviceInfo> records);
}