package com.homw.gateway.common.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.homw.gateway.entity.DeviceElectricUseInfo;
import com.homw.gateway.entity.example.DeviceElectricUseInfoExample;

public interface DeviceElectricUseInfoDao {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int countByExample(DeviceElectricUseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceElectricUseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long deviceUseInfoId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int insert(DeviceElectricUseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int insertSelective(DeviceElectricUseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    List<DeviceElectricUseInfo> selectByExample(DeviceElectricUseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    DeviceElectricUseInfo selectByPrimaryKey(Long deviceUseInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceElectricUseInfo record, @Param("example") DeviceElectricUseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceElectricUseInfo record, @Param("example") DeviceElectricUseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceElectricUseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceElectricUseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    List<Long> selectIdsByExample(DeviceElectricUseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    Integer batchInsert(List<DeviceElectricUseInfo> records);
    
    Integer getNearMaxDay(Map<String ,Object> map);
}