package com.homw.gateway.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.homw.gateway.entity.JobMessage;
import com.homw.gateway.entity.example.JobMessageExample;

public interface JobMessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int countByExample(JobMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int deleteByExample(JobMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long jobMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int insert(JobMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int insertSelective(JobMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    List<JobMessage> selectByExample(JobMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    JobMessage selectByPrimaryKey(Long jobMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JobMessage record, @Param("example") JobMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JobMessage record, @Param("example") JobMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JobMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JobMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    List<Long> selectIdsByExample(JobMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    Integer batchInsert(List<JobMessage> records);
}