package com.homw.gateway.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.homw.gateway.entity.Sign;
import com.homw.gateway.entity.example.SignExample;

public interface SignDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int countByExample(SignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int deleteByExample(SignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int insert(Sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int insertSelective(Sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    List<Sign> selectByExample(SignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    Sign selectByPrimaryKey(Long signId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Sign record, @Param("example") SignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Sign record, @Param("example") SignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    List<Long> selectIdsByExample(SignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_sign
     *
     * @mbggenerated
     */
    Integer batchInsert(List<Sign> records);
}