package com.homw.gateway.entity.example;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DeviceInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    protected static final Map<String, String> property2column = new HashMap<String, String>();

    protected Long start;

    protected Long count;

    protected String groupBy;

    static {
        property2column.put("deviceId", "DEVICE_ID");
        property2column.put("deviceType", "DEVICE_TYPE");
        property2column.put("outerNo", "OUTER_NO");
        property2column.put("doorIp", "DOOR_IP");
        property2column.put("doorPort", "DOOR_PORT");
        property2column.put("doorAddr", "DOOR_ADDR");
        property2column.put("doorReadno", "DOOR_READNO");
        property2column.put("doorName", "DOOR_NAME");
        property2column.put("elecAddr", "ELEC_ADDR");
        property2column.put("elecStatus", "ELEC_STATUS");
        property2column.put("elecUsePoint", "ELEC_USE_POINT");
        property2column.put("elecLeftPoint", "ELEC_LEFT_POINT");
        property2column.put("status", "STATUS");
        property2column.put("version", "VERSION");
        property2column.put("createUserId", "CREATE_USER_ID");
        property2column.put("createTime", "CREATE_TIME");
        property2column.put("createUserType", "CREATE_USER_TYPE");
        property2column.put("updateUserId", "UPDATE_USER_ID");
        property2column.put("updateTime", "UPDATE_TIME");
        property2column.put("updateUserType", "UPDATE_USER_TYPE");
        property2column.put("referElecId", "REFER_ELEC_ID");
        property2column.put("isReferNode", "IS_REFER_NODE");
        property2column.put("rate", "RATE");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public DeviceInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public static String getColumn(String property) {
        return property2column.get(property);
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public Long getStart() {
        return start;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public Long getCount() {
        return count;
    }

    public void setGroupBy(String groupBy) {
        this.groupBy = groupBy;
    }

    public String getGroupBy() {
        return groupBy;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("DEVICE_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("DEVICE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("DEVICE_ID =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("DEVICE_ID <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("DEVICE_ID >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEVICE_ID >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("DEVICE_ID <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("DEVICE_ID <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("DEVICE_ID in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("DEVICE_ID not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("DEVICE_ID between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("DEVICE_ID not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNull() {
            addCriterion("DEVICE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNotNull() {
            addCriterion("DEVICE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeEqualTo(String value) {
            addCriterion("DEVICE_TYPE =", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotEqualTo(String value) {
            addCriterion("DEVICE_TYPE <>", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThan(String value) {
            addCriterion("DEVICE_TYPE >", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DEVICE_TYPE >=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThan(String value) {
            addCriterion("DEVICE_TYPE <", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
            addCriterion("DEVICE_TYPE <=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLike(String value) {
            addCriterion("DEVICE_TYPE like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotLike(String value) {
            addCriterion("DEVICE_TYPE not like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIn(List<String> values) {
            addCriterion("DEVICE_TYPE in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotIn(List<String> values) {
            addCriterion("DEVICE_TYPE not in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeBetween(String value1, String value2) {
            addCriterion("DEVICE_TYPE between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotBetween(String value1, String value2) {
            addCriterion("DEVICE_TYPE not between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andOuterNoIsNull() {
            addCriterion("OUTER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOuterNoIsNotNull() {
            addCriterion("OUTER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOuterNoEqualTo(String value) {
            addCriterion("OUTER_NO =", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoNotEqualTo(String value) {
            addCriterion("OUTER_NO <>", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoGreaterThan(String value) {
            addCriterion("OUTER_NO >", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoGreaterThanOrEqualTo(String value) {
            addCriterion("OUTER_NO >=", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoLessThan(String value) {
            addCriterion("OUTER_NO <", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoLessThanOrEqualTo(String value) {
            addCriterion("OUTER_NO <=", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoLike(String value) {
            addCriterion("OUTER_NO like", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoNotLike(String value) {
            addCriterion("OUTER_NO not like", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoIn(List<String> values) {
            addCriterion("OUTER_NO in", values, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoNotIn(List<String> values) {
            addCriterion("OUTER_NO not in", values, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoBetween(String value1, String value2) {
            addCriterion("OUTER_NO between", value1, value2, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoNotBetween(String value1, String value2) {
            addCriterion("OUTER_NO not between", value1, value2, "outerNo");
            return (Criteria) this;
        }

        public Criteria andDoorIpIsNull() {
            addCriterion("DOOR_IP is null");
            return (Criteria) this;
        }

        public Criteria andDoorIpIsNotNull() {
            addCriterion("DOOR_IP is not null");
            return (Criteria) this;
        }

        public Criteria andDoorIpEqualTo(String value) {
            addCriterion("DOOR_IP =", value, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpNotEqualTo(String value) {
            addCriterion("DOOR_IP <>", value, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpGreaterThan(String value) {
            addCriterion("DOOR_IP >", value, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpGreaterThanOrEqualTo(String value) {
            addCriterion("DOOR_IP >=", value, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpLessThan(String value) {
            addCriterion("DOOR_IP <", value, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpLessThanOrEqualTo(String value) {
            addCriterion("DOOR_IP <=", value, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpLike(String value) {
            addCriterion("DOOR_IP like", value, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpNotLike(String value) {
            addCriterion("DOOR_IP not like", value, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpIn(List<String> values) {
            addCriterion("DOOR_IP in", values, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpNotIn(List<String> values) {
            addCriterion("DOOR_IP not in", values, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpBetween(String value1, String value2) {
            addCriterion("DOOR_IP between", value1, value2, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorIpNotBetween(String value1, String value2) {
            addCriterion("DOOR_IP not between", value1, value2, "doorIp");
            return (Criteria) this;
        }

        public Criteria andDoorPortIsNull() {
            addCriterion("DOOR_PORT is null");
            return (Criteria) this;
        }

        public Criteria andDoorPortIsNotNull() {
            addCriterion("DOOR_PORT is not null");
            return (Criteria) this;
        }

        public Criteria andDoorPortEqualTo(Integer value) {
            addCriterion("DOOR_PORT =", value, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortNotEqualTo(Integer value) {
            addCriterion("DOOR_PORT <>", value, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortGreaterThan(Integer value) {
            addCriterion("DOOR_PORT >", value, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("DOOR_PORT >=", value, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortLessThan(Integer value) {
            addCriterion("DOOR_PORT <", value, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortLessThanOrEqualTo(Integer value) {
            addCriterion("DOOR_PORT <=", value, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortIn(List<Integer> values) {
            addCriterion("DOOR_PORT in", values, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortNotIn(List<Integer> values) {
            addCriterion("DOOR_PORT not in", values, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortBetween(Integer value1, Integer value2) {
            addCriterion("DOOR_PORT between", value1, value2, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorPortNotBetween(Integer value1, Integer value2) {
            addCriterion("DOOR_PORT not between", value1, value2, "doorPort");
            return (Criteria) this;
        }

        public Criteria andDoorAddrIsNull() {
            addCriterion("DOOR_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andDoorAddrIsNotNull() {
            addCriterion("DOOR_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andDoorAddrEqualTo(String value) {
            addCriterion("DOOR_ADDR =", value, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrNotEqualTo(String value) {
            addCriterion("DOOR_ADDR <>", value, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrGreaterThan(String value) {
            addCriterion("DOOR_ADDR >", value, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrGreaterThanOrEqualTo(String value) {
            addCriterion("DOOR_ADDR >=", value, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrLessThan(String value) {
            addCriterion("DOOR_ADDR <", value, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrLessThanOrEqualTo(String value) {
            addCriterion("DOOR_ADDR <=", value, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrLike(String value) {
            addCriterion("DOOR_ADDR like", value, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrNotLike(String value) {
            addCriterion("DOOR_ADDR not like", value, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrIn(List<String> values) {
            addCriterion("DOOR_ADDR in", values, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrNotIn(List<String> values) {
            addCriterion("DOOR_ADDR not in", values, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrBetween(String value1, String value2) {
            addCriterion("DOOR_ADDR between", value1, value2, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorAddrNotBetween(String value1, String value2) {
            addCriterion("DOOR_ADDR not between", value1, value2, "doorAddr");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoIsNull() {
            addCriterion("DOOR_READNO is null");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoIsNotNull() {
            addCriterion("DOOR_READNO is not null");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoEqualTo(Integer value) {
            addCriterion("DOOR_READNO =", value, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoNotEqualTo(Integer value) {
            addCriterion("DOOR_READNO <>", value, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoGreaterThan(Integer value) {
            addCriterion("DOOR_READNO >", value, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("DOOR_READNO >=", value, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoLessThan(Integer value) {
            addCriterion("DOOR_READNO <", value, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoLessThanOrEqualTo(Integer value) {
            addCriterion("DOOR_READNO <=", value, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoIn(List<Integer> values) {
            addCriterion("DOOR_READNO in", values, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoNotIn(List<Integer> values) {
            addCriterion("DOOR_READNO not in", values, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoBetween(Integer value1, Integer value2) {
            addCriterion("DOOR_READNO between", value1, value2, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorReadnoNotBetween(Integer value1, Integer value2) {
            addCriterion("DOOR_READNO not between", value1, value2, "doorReadno");
            return (Criteria) this;
        }

        public Criteria andDoorNameIsNull() {
            addCriterion("DOOR_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDoorNameIsNotNull() {
            addCriterion("DOOR_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDoorNameEqualTo(String value) {
            addCriterion("DOOR_NAME =", value, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameNotEqualTo(String value) {
            addCriterion("DOOR_NAME <>", value, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameGreaterThan(String value) {
            addCriterion("DOOR_NAME >", value, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameGreaterThanOrEqualTo(String value) {
            addCriterion("DOOR_NAME >=", value, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameLessThan(String value) {
            addCriterion("DOOR_NAME <", value, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameLessThanOrEqualTo(String value) {
            addCriterion("DOOR_NAME <=", value, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameLike(String value) {
            addCriterion("DOOR_NAME like", value, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameNotLike(String value) {
            addCriterion("DOOR_NAME not like", value, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameIn(List<String> values) {
            addCriterion("DOOR_NAME in", values, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameNotIn(List<String> values) {
            addCriterion("DOOR_NAME not in", values, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameBetween(String value1, String value2) {
            addCriterion("DOOR_NAME between", value1, value2, "doorName");
            return (Criteria) this;
        }

        public Criteria andDoorNameNotBetween(String value1, String value2) {
            addCriterion("DOOR_NAME not between", value1, value2, "doorName");
            return (Criteria) this;
        }

        public Criteria andElecAddrIsNull() {
            addCriterion("ELEC_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andElecAddrIsNotNull() {
            addCriterion("ELEC_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andElecAddrEqualTo(String value) {
            addCriterion("ELEC_ADDR =", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotEqualTo(String value) {
            addCriterion("ELEC_ADDR <>", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrGreaterThan(String value) {
            addCriterion("ELEC_ADDR >", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ELEC_ADDR >=", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLessThan(String value) {
            addCriterion("ELEC_ADDR <", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLessThanOrEqualTo(String value) {
            addCriterion("ELEC_ADDR <=", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLike(String value) {
            addCriterion("ELEC_ADDR like", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotLike(String value) {
            addCriterion("ELEC_ADDR not like", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrIn(List<String> values) {
            addCriterion("ELEC_ADDR in", values, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotIn(List<String> values) {
            addCriterion("ELEC_ADDR not in", values, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrBetween(String value1, String value2) {
            addCriterion("ELEC_ADDR between", value1, value2, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotBetween(String value1, String value2) {
            addCriterion("ELEC_ADDR not between", value1, value2, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecStatusIsNull() {
            addCriterion("ELEC_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andElecStatusIsNotNull() {
            addCriterion("ELEC_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andElecStatusEqualTo(String value) {
            addCriterion("ELEC_STATUS =", value, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusNotEqualTo(String value) {
            addCriterion("ELEC_STATUS <>", value, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusGreaterThan(String value) {
            addCriterion("ELEC_STATUS >", value, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ELEC_STATUS >=", value, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusLessThan(String value) {
            addCriterion("ELEC_STATUS <", value, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusLessThanOrEqualTo(String value) {
            addCriterion("ELEC_STATUS <=", value, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusLike(String value) {
            addCriterion("ELEC_STATUS like", value, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusNotLike(String value) {
            addCriterion("ELEC_STATUS not like", value, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusIn(List<String> values) {
            addCriterion("ELEC_STATUS in", values, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusNotIn(List<String> values) {
            addCriterion("ELEC_STATUS not in", values, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusBetween(String value1, String value2) {
            addCriterion("ELEC_STATUS between", value1, value2, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecStatusNotBetween(String value1, String value2) {
            addCriterion("ELEC_STATUS not between", value1, value2, "elecStatus");
            return (Criteria) this;
        }

        public Criteria andElecUsePointIsNull() {
            addCriterion("ELEC_USE_POINT is null");
            return (Criteria) this;
        }

        public Criteria andElecUsePointIsNotNull() {
            addCriterion("ELEC_USE_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andElecUsePointEqualTo(Integer value) {
            addCriterion("ELEC_USE_POINT =", value, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointNotEqualTo(Integer value) {
            addCriterion("ELEC_USE_POINT <>", value, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointGreaterThan(Integer value) {
            addCriterion("ELEC_USE_POINT >", value, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointGreaterThanOrEqualTo(Integer value) {
            addCriterion("ELEC_USE_POINT >=", value, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointLessThan(Integer value) {
            addCriterion("ELEC_USE_POINT <", value, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointLessThanOrEqualTo(Integer value) {
            addCriterion("ELEC_USE_POINT <=", value, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointIn(List<Integer> values) {
            addCriterion("ELEC_USE_POINT in", values, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointNotIn(List<Integer> values) {
            addCriterion("ELEC_USE_POINT not in", values, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointBetween(Integer value1, Integer value2) {
            addCriterion("ELEC_USE_POINT between", value1, value2, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecUsePointNotBetween(Integer value1, Integer value2) {
            addCriterion("ELEC_USE_POINT not between", value1, value2, "elecUsePoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointIsNull() {
            addCriterion("ELEC_LEFT_POINT is null");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointIsNotNull() {
            addCriterion("ELEC_LEFT_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointEqualTo(Integer value) {
            addCriterion("ELEC_LEFT_POINT =", value, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointNotEqualTo(Integer value) {
            addCriterion("ELEC_LEFT_POINT <>", value, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointGreaterThan(Integer value) {
            addCriterion("ELEC_LEFT_POINT >", value, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("ELEC_LEFT_POINT >=", value, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointLessThan(Integer value) {
            addCriterion("ELEC_LEFT_POINT <", value, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointLessThanOrEqualTo(Integer value) {
            addCriterion("ELEC_LEFT_POINT <=", value, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointIn(List<Integer> values) {
            addCriterion("ELEC_LEFT_POINT in", values, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointNotIn(List<Integer> values) {
            addCriterion("ELEC_LEFT_POINT not in", values, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointBetween(Integer value1, Integer value2) {
            addCriterion("ELEC_LEFT_POINT between", value1, value2, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andElecLeftPointNotBetween(Integer value1, Integer value2) {
            addCriterion("ELEC_LEFT_POINT not between", value1, value2, "elecLeftPoint");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeIsNull() {
            addCriterion("CREATE_USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeIsNotNull() {
            addCriterion("CREATE_USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeEqualTo(String value) {
            addCriterion("CREATE_USER_TYPE =", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeNotEqualTo(String value) {
            addCriterion("CREATE_USER_TYPE <>", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeGreaterThan(String value) {
            addCriterion("CREATE_USER_TYPE >", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_TYPE >=", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeLessThan(String value) {
            addCriterion("CREATE_USER_TYPE <", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_TYPE <=", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeLike(String value) {
            addCriterion("CREATE_USER_TYPE like", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeNotLike(String value) {
            addCriterion("CREATE_USER_TYPE not like", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeIn(List<String> values) {
            addCriterion("CREATE_USER_TYPE in", values, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeNotIn(List<String> values) {
            addCriterion("CREATE_USER_TYPE not in", values, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeBetween(String value1, String value2) {
            addCriterion("CREATE_USER_TYPE between", value1, value2, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_TYPE not between", value1, value2, "createUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(Long value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(Long value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(Long value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(Long value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<Long> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<Long> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(Long value1, Long value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Long value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Long value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Long value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Long value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Long value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Long> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Long> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Long value1, Long value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Long value1, Long value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeIsNull() {
            addCriterion("UPDATE_USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeIsNotNull() {
            addCriterion("UPDATE_USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeEqualTo(String value) {
            addCriterion("UPDATE_USER_TYPE =", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeNotEqualTo(String value) {
            addCriterion("UPDATE_USER_TYPE <>", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeGreaterThan(String value) {
            addCriterion("UPDATE_USER_TYPE >", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_TYPE >=", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeLessThan(String value) {
            addCriterion("UPDATE_USER_TYPE <", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_TYPE <=", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeLike(String value) {
            addCriterion("UPDATE_USER_TYPE like", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeNotLike(String value) {
            addCriterion("UPDATE_USER_TYPE not like", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeIn(List<String> values) {
            addCriterion("UPDATE_USER_TYPE in", values, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeNotIn(List<String> values) {
            addCriterion("UPDATE_USER_TYPE not in", values, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_TYPE between", value1, value2, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_TYPE not between", value1, value2, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andReferElecIdIsNull() {
            addCriterion("REFER_ELEC_ID is null");
            return (Criteria) this;
        }

        public Criteria andReferElecIdIsNotNull() {
            addCriterion("REFER_ELEC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andReferElecIdEqualTo(Long value) {
            addCriterion("REFER_ELEC_ID =", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdNotEqualTo(Long value) {
            addCriterion("REFER_ELEC_ID <>", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdGreaterThan(Long value) {
            addCriterion("REFER_ELEC_ID >", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("REFER_ELEC_ID >=", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdLessThan(Long value) {
            addCriterion("REFER_ELEC_ID <", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdLessThanOrEqualTo(Long value) {
            addCriterion("REFER_ELEC_ID <=", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdIn(List<Long> values) {
            addCriterion("REFER_ELEC_ID in", values, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdNotIn(List<Long> values) {
            addCriterion("REFER_ELEC_ID not in", values, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdBetween(Long value1, Long value2) {
            addCriterion("REFER_ELEC_ID between", value1, value2, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdNotBetween(Long value1, Long value2) {
            addCriterion("REFER_ELEC_ID not between", value1, value2, "referElecId");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeIsNull() {
            addCriterion("IS_REFER_NODE is null");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeIsNotNull() {
            addCriterion("IS_REFER_NODE is not null");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeEqualTo(Boolean value) {
            addCriterion("IS_REFER_NODE =", value, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeNotEqualTo(Boolean value) {
            addCriterion("IS_REFER_NODE <>", value, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeGreaterThan(Boolean value) {
            addCriterion("IS_REFER_NODE >", value, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_REFER_NODE >=", value, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeLessThan(Boolean value) {
            addCriterion("IS_REFER_NODE <", value, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_REFER_NODE <=", value, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeIn(List<Boolean> values) {
            addCriterion("IS_REFER_NODE in", values, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeNotIn(List<Boolean> values) {
            addCriterion("IS_REFER_NODE not in", values, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_REFER_NODE between", value1, value2, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andIsReferNodeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_REFER_NODE not between", value1, value2, "isReferNode");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("RATE is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("RATE is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(Integer value) {
            addCriterion("RATE =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(Integer value) {
            addCriterion("RATE <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(Integer value) {
            addCriterion("RATE >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("RATE >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(Integer value) {
            addCriterion("RATE <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(Integer value) {
            addCriterion("RATE <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<Integer> values) {
            addCriterion("RATE in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<Integer> values) {
            addCriterion("RATE not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(Integer value1, Integer value2) {
            addCriterion("RATE between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(Integer value1, Integer value2) {
            addCriterion("RATE not between", value1, value2, "rate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}