package com.homw.gateway.entity.example;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DeviceElectricUseInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    protected static final Map<String, String> property2column = new HashMap<String, String>();

    protected Long start;

    protected Long count;

    protected String groupBy;

    static {
        property2column.put("deviceUseInfoId", "DEVICE_USE_INFO_ID");
        property2column.put("outerNo", "OUTER_NO");
        property2column.put("elecAddr", "ELEC_ADDR");
        property2column.put("yesday", "YESDAY");
        property2column.put("nowday", "NOWDAY");
        property2column.put("yesdayPoint", "YESDAY_POINT");
        property2column.put("nowdayPoint", "NOWDAY_POINT");
        property2column.put("curUsePoint", "CUR_USE_POINT");
        property2column.put("otherUsePoint", "OTHER_USE_POINT");
        property2column.put("status", "STATUS");
        property2column.put("version", "VERSION");
        property2column.put("createTime", "CREATE_TIME");
        property2column.put("updateTime", "UPDATE_TIME");
        property2column.put("referElecId", "REFER_ELEC_ID");
        property2column.put("deviceId", "DEVICE_ID");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public DeviceElectricUseInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public static String getColumn(String property) {
        return property2column.get(property);
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public Long getStart() {
        return start;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public Long getCount() {
        return count;
    }

    public void setGroupBy(String groupBy) {
        this.groupBy = groupBy;
    }

    public String getGroupBy() {
        return groupBy;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDeviceUseInfoIdIsNull() {
            addCriterion("DEVICE_USE_INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdIsNotNull() {
            addCriterion("DEVICE_USE_INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdEqualTo(Long value) {
            addCriterion("DEVICE_USE_INFO_ID =", value, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdNotEqualTo(Long value) {
            addCriterion("DEVICE_USE_INFO_ID <>", value, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdGreaterThan(Long value) {
            addCriterion("DEVICE_USE_INFO_ID >", value, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEVICE_USE_INFO_ID >=", value, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdLessThan(Long value) {
            addCriterion("DEVICE_USE_INFO_ID <", value, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("DEVICE_USE_INFO_ID <=", value, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdIn(List<Long> values) {
            addCriterion("DEVICE_USE_INFO_ID in", values, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdNotIn(List<Long> values) {
            addCriterion("DEVICE_USE_INFO_ID not in", values, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdBetween(Long value1, Long value2) {
            addCriterion("DEVICE_USE_INFO_ID between", value1, value2, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andDeviceUseInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("DEVICE_USE_INFO_ID not between", value1, value2, "deviceUseInfoId");
            return (Criteria) this;
        }

        public Criteria andOuterNoIsNull() {
            addCriterion("OUTER_NO is null");
            return (Criteria) this;
        }

        public Criteria andOuterNoIsNotNull() {
            addCriterion("OUTER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOuterNoEqualTo(String value) {
            addCriterion("OUTER_NO =", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoNotEqualTo(String value) {
            addCriterion("OUTER_NO <>", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoGreaterThan(String value) {
            addCriterion("OUTER_NO >", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoGreaterThanOrEqualTo(String value) {
            addCriterion("OUTER_NO >=", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoLessThan(String value) {
            addCriterion("OUTER_NO <", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoLessThanOrEqualTo(String value) {
            addCriterion("OUTER_NO <=", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoLike(String value) {
            addCriterion("OUTER_NO like", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoNotLike(String value) {
            addCriterion("OUTER_NO not like", value, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoIn(List<String> values) {
            addCriterion("OUTER_NO in", values, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoNotIn(List<String> values) {
            addCriterion("OUTER_NO not in", values, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoBetween(String value1, String value2) {
            addCriterion("OUTER_NO between", value1, value2, "outerNo");
            return (Criteria) this;
        }

        public Criteria andOuterNoNotBetween(String value1, String value2) {
            addCriterion("OUTER_NO not between", value1, value2, "outerNo");
            return (Criteria) this;
        }

        public Criteria andElecAddrIsNull() {
            addCriterion("ELEC_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andElecAddrIsNotNull() {
            addCriterion("ELEC_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andElecAddrEqualTo(String value) {
            addCriterion("ELEC_ADDR =", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotEqualTo(String value) {
            addCriterion("ELEC_ADDR <>", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrGreaterThan(String value) {
            addCriterion("ELEC_ADDR >", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrGreaterThanOrEqualTo(String value) {
            addCriterion("ELEC_ADDR >=", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLessThan(String value) {
            addCriterion("ELEC_ADDR <", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLessThanOrEqualTo(String value) {
            addCriterion("ELEC_ADDR <=", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrLike(String value) {
            addCriterion("ELEC_ADDR like", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotLike(String value) {
            addCriterion("ELEC_ADDR not like", value, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrIn(List<String> values) {
            addCriterion("ELEC_ADDR in", values, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotIn(List<String> values) {
            addCriterion("ELEC_ADDR not in", values, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrBetween(String value1, String value2) {
            addCriterion("ELEC_ADDR between", value1, value2, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andElecAddrNotBetween(String value1, String value2) {
            addCriterion("ELEC_ADDR not between", value1, value2, "elecAddr");
            return (Criteria) this;
        }

        public Criteria andYesdayIsNull() {
            addCriterion("YESDAY is null");
            return (Criteria) this;
        }

        public Criteria andYesdayIsNotNull() {
            addCriterion("YESDAY is not null");
            return (Criteria) this;
        }

        public Criteria andYesdayEqualTo(String value) {
            addCriterion("YESDAY =", value, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayNotEqualTo(String value) {
            addCriterion("YESDAY <>", value, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayGreaterThan(String value) {
            addCriterion("YESDAY >", value, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayGreaterThanOrEqualTo(String value) {
            addCriterion("YESDAY >=", value, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayLessThan(String value) {
            addCriterion("YESDAY <", value, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayLessThanOrEqualTo(String value) {
            addCriterion("YESDAY <=", value, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayLike(String value) {
            addCriterion("YESDAY like", value, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayNotLike(String value) {
            addCriterion("YESDAY not like", value, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayIn(List<String> values) {
            addCriterion("YESDAY in", values, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayNotIn(List<String> values) {
            addCriterion("YESDAY not in", values, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayBetween(String value1, String value2) {
            addCriterion("YESDAY between", value1, value2, "yesday");
            return (Criteria) this;
        }

        public Criteria andYesdayNotBetween(String value1, String value2) {
            addCriterion("YESDAY not between", value1, value2, "yesday");
            return (Criteria) this;
        }

        public Criteria andNowdayIsNull() {
            addCriterion("NOWDAY is null");
            return (Criteria) this;
        }

        public Criteria andNowdayIsNotNull() {
            addCriterion("NOWDAY is not null");
            return (Criteria) this;
        }

        public Criteria andNowdayEqualTo(String value) {
            addCriterion("NOWDAY =", value, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayNotEqualTo(String value) {
            addCriterion("NOWDAY <>", value, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayGreaterThan(String value) {
            addCriterion("NOWDAY >", value, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayGreaterThanOrEqualTo(String value) {
            addCriterion("NOWDAY >=", value, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayLessThan(String value) {
            addCriterion("NOWDAY <", value, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayLessThanOrEqualTo(String value) {
            addCriterion("NOWDAY <=", value, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayLike(String value) {
            addCriterion("NOWDAY like", value, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayNotLike(String value) {
            addCriterion("NOWDAY not like", value, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayIn(List<String> values) {
            addCriterion("NOWDAY in", values, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayNotIn(List<String> values) {
            addCriterion("NOWDAY not in", values, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayBetween(String value1, String value2) {
            addCriterion("NOWDAY between", value1, value2, "nowday");
            return (Criteria) this;
        }

        public Criteria andNowdayNotBetween(String value1, String value2) {
            addCriterion("NOWDAY not between", value1, value2, "nowday");
            return (Criteria) this;
        }

        public Criteria andYesdayPointIsNull() {
            addCriterion("YESDAY_POINT is null");
            return (Criteria) this;
        }

        public Criteria andYesdayPointIsNotNull() {
            addCriterion("YESDAY_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andYesdayPointEqualTo(Integer value) {
            addCriterion("YESDAY_POINT =", value, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointNotEqualTo(Integer value) {
            addCriterion("YESDAY_POINT <>", value, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointGreaterThan(Integer value) {
            addCriterion("YESDAY_POINT >", value, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("YESDAY_POINT >=", value, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointLessThan(Integer value) {
            addCriterion("YESDAY_POINT <", value, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointLessThanOrEqualTo(Integer value) {
            addCriterion("YESDAY_POINT <=", value, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointIn(List<Integer> values) {
            addCriterion("YESDAY_POINT in", values, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointNotIn(List<Integer> values) {
            addCriterion("YESDAY_POINT not in", values, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointBetween(Integer value1, Integer value2) {
            addCriterion("YESDAY_POINT between", value1, value2, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andYesdayPointNotBetween(Integer value1, Integer value2) {
            addCriterion("YESDAY_POINT not between", value1, value2, "yesdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointIsNull() {
            addCriterion("NOWDAY_POINT is null");
            return (Criteria) this;
        }

        public Criteria andNowdayPointIsNotNull() {
            addCriterion("NOWDAY_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andNowdayPointEqualTo(Integer value) {
            addCriterion("NOWDAY_POINT =", value, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointNotEqualTo(Integer value) {
            addCriterion("NOWDAY_POINT <>", value, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointGreaterThan(Integer value) {
            addCriterion("NOWDAY_POINT >", value, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("NOWDAY_POINT >=", value, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointLessThan(Integer value) {
            addCriterion("NOWDAY_POINT <", value, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointLessThanOrEqualTo(Integer value) {
            addCriterion("NOWDAY_POINT <=", value, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointIn(List<Integer> values) {
            addCriterion("NOWDAY_POINT in", values, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointNotIn(List<Integer> values) {
            addCriterion("NOWDAY_POINT not in", values, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointBetween(Integer value1, Integer value2) {
            addCriterion("NOWDAY_POINT between", value1, value2, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andNowdayPointNotBetween(Integer value1, Integer value2) {
            addCriterion("NOWDAY_POINT not between", value1, value2, "nowdayPoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointIsNull() {
            addCriterion("CUR_USE_POINT is null");
            return (Criteria) this;
        }

        public Criteria andCurUsePointIsNotNull() {
            addCriterion("CUR_USE_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andCurUsePointEqualTo(Integer value) {
            addCriterion("CUR_USE_POINT =", value, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointNotEqualTo(Integer value) {
            addCriterion("CUR_USE_POINT <>", value, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointGreaterThan(Integer value) {
            addCriterion("CUR_USE_POINT >", value, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUR_USE_POINT >=", value, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointLessThan(Integer value) {
            addCriterion("CUR_USE_POINT <", value, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointLessThanOrEqualTo(Integer value) {
            addCriterion("CUR_USE_POINT <=", value, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointIn(List<Integer> values) {
            addCriterion("CUR_USE_POINT in", values, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointNotIn(List<Integer> values) {
            addCriterion("CUR_USE_POINT not in", values, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointBetween(Integer value1, Integer value2) {
            addCriterion("CUR_USE_POINT between", value1, value2, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andCurUsePointNotBetween(Integer value1, Integer value2) {
            addCriterion("CUR_USE_POINT not between", value1, value2, "curUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointIsNull() {
            addCriterion("OTHER_USE_POINT is null");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointIsNotNull() {
            addCriterion("OTHER_USE_POINT is not null");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointEqualTo(Integer value) {
            addCriterion("OTHER_USE_POINT =", value, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointNotEqualTo(Integer value) {
            addCriterion("OTHER_USE_POINT <>", value, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointGreaterThan(Integer value) {
            addCriterion("OTHER_USE_POINT >", value, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointGreaterThanOrEqualTo(Integer value) {
            addCriterion("OTHER_USE_POINT >=", value, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointLessThan(Integer value) {
            addCriterion("OTHER_USE_POINT <", value, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointLessThanOrEqualTo(Integer value) {
            addCriterion("OTHER_USE_POINT <=", value, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointIn(List<Integer> values) {
            addCriterion("OTHER_USE_POINT in", values, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointNotIn(List<Integer> values) {
            addCriterion("OTHER_USE_POINT not in", values, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointBetween(Integer value1, Integer value2) {
            addCriterion("OTHER_USE_POINT between", value1, value2, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andOtherUsePointNotBetween(Integer value1, Integer value2) {
            addCriterion("OTHER_USE_POINT not between", value1, value2, "otherUsePoint");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Long value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Long value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Long value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Long value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Long value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Long> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Long> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Long value1, Long value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Long value1, Long value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andReferElecIdIsNull() {
            addCriterion("REFER_ELEC_ID is null");
            return (Criteria) this;
        }

        public Criteria andReferElecIdIsNotNull() {
            addCriterion("REFER_ELEC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andReferElecIdEqualTo(Long value) {
            addCriterion("REFER_ELEC_ID =", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdNotEqualTo(Long value) {
            addCriterion("REFER_ELEC_ID <>", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdGreaterThan(Long value) {
            addCriterion("REFER_ELEC_ID >", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("REFER_ELEC_ID >=", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdLessThan(Long value) {
            addCriterion("REFER_ELEC_ID <", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdLessThanOrEqualTo(Long value) {
            addCriterion("REFER_ELEC_ID <=", value, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdIn(List<Long> values) {
            addCriterion("REFER_ELEC_ID in", values, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdNotIn(List<Long> values) {
            addCriterion("REFER_ELEC_ID not in", values, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdBetween(Long value1, Long value2) {
            addCriterion("REFER_ELEC_ID between", value1, value2, "referElecId");
            return (Criteria) this;
        }

        public Criteria andReferElecIdNotBetween(Long value1, Long value2) {
            addCriterion("REFER_ELEC_ID not between", value1, value2, "referElecId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("DEVICE_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("DEVICE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("DEVICE_ID =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("DEVICE_ID <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("DEVICE_ID >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DEVICE_ID >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("DEVICE_ID <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("DEVICE_ID <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("DEVICE_ID in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("DEVICE_ID not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("DEVICE_ID between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("DEVICE_ID not between", value1, value2, "deviceId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_electric_use_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_electric_use_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}