package com.homw.gateway.entity.example;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class JobMessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    protected static final Map<String, String> property2column = new HashMap<String, String>();

    protected Long start;

    protected Long count;

    protected String groupBy;

    static {
        property2column.put("jobMessageId", "JOB_MESSAGE_ID");
        property2column.put("jobName", "JOB_NAME");
        property2column.put("jobGroup", "JOB_GROUP");
        property2column.put("jobCronexpression", "JOB_CRONEXPRESSION");
        property2column.put("jobDescription", "JOB_DESCRIPTION");
        property2column.put("buinessType", "BUINESS_TYPE");
        property2column.put("buinessId", "BUINESS_ID");
        property2column.put("jobStatus", "JOB_STATUS");
        property2column.put("remarks", "REMARKS");
        property2column.put("status", "STATUS");
        property2column.put("version", "VERSION");
        property2column.put("createUserId", "CREATE_USER_ID");
        property2column.put("createTime", "CREATE_TIME");
        property2column.put("createUserType", "CREATE_USER_TYPE");
        property2column.put("updateUserId", "UPDATE_USER_ID");
        property2column.put("updateTime", "UPDATE_TIME");
        property2column.put("updateUserType", "UPDATE_USER_TYPE");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public JobMessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public static String getColumn(String property) {
        return property2column.get(property);
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public Long getStart() {
        return start;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public Long getCount() {
        return count;
    }

    public void setGroupBy(String groupBy) {
        this.groupBy = groupBy;
    }

    public String getGroupBy() {
        return groupBy;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobMessageIdIsNull() {
            addCriterion("JOB_MESSAGE_ID is null");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdIsNotNull() {
            addCriterion("JOB_MESSAGE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdEqualTo(Long value) {
            addCriterion("JOB_MESSAGE_ID =", value, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdNotEqualTo(Long value) {
            addCriterion("JOB_MESSAGE_ID <>", value, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdGreaterThan(Long value) {
            addCriterion("JOB_MESSAGE_ID >", value, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdGreaterThanOrEqualTo(Long value) {
            addCriterion("JOB_MESSAGE_ID >=", value, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdLessThan(Long value) {
            addCriterion("JOB_MESSAGE_ID <", value, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdLessThanOrEqualTo(Long value) {
            addCriterion("JOB_MESSAGE_ID <=", value, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdIn(List<Long> values) {
            addCriterion("JOB_MESSAGE_ID in", values, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdNotIn(List<Long> values) {
            addCriterion("JOB_MESSAGE_ID not in", values, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdBetween(Long value1, Long value2) {
            addCriterion("JOB_MESSAGE_ID between", value1, value2, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobMessageIdNotBetween(Long value1, Long value2) {
            addCriterion("JOB_MESSAGE_ID not between", value1, value2, "jobMessageId");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("JOB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("JOB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("JOB_NAME =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("JOB_NAME <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("JOB_NAME >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_NAME >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("JOB_NAME <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("JOB_NAME <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("JOB_NAME like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("JOB_NAME not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("JOB_NAME in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("JOB_NAME not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("JOB_NAME between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("JOB_NAME not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobGroupIsNull() {
            addCriterion("JOB_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andJobGroupIsNotNull() {
            addCriterion("JOB_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andJobGroupEqualTo(String value) {
            addCriterion("JOB_GROUP =", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotEqualTo(String value) {
            addCriterion("JOB_GROUP <>", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupGreaterThan(String value) {
            addCriterion("JOB_GROUP >", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_GROUP >=", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLessThan(String value) {
            addCriterion("JOB_GROUP <", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLessThanOrEqualTo(String value) {
            addCriterion("JOB_GROUP <=", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupLike(String value) {
            addCriterion("JOB_GROUP like", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotLike(String value) {
            addCriterion("JOB_GROUP not like", value, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupIn(List<String> values) {
            addCriterion("JOB_GROUP in", values, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotIn(List<String> values) {
            addCriterion("JOB_GROUP not in", values, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupBetween(String value1, String value2) {
            addCriterion("JOB_GROUP between", value1, value2, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobGroupNotBetween(String value1, String value2) {
            addCriterion("JOB_GROUP not between", value1, value2, "jobGroup");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionIsNull() {
            addCriterion("JOB_CRONEXPRESSION is null");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionIsNotNull() {
            addCriterion("JOB_CRONEXPRESSION is not null");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionEqualTo(String value) {
            addCriterion("JOB_CRONEXPRESSION =", value, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionNotEqualTo(String value) {
            addCriterion("JOB_CRONEXPRESSION <>", value, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionGreaterThan(String value) {
            addCriterion("JOB_CRONEXPRESSION >", value, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_CRONEXPRESSION >=", value, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionLessThan(String value) {
            addCriterion("JOB_CRONEXPRESSION <", value, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionLessThanOrEqualTo(String value) {
            addCriterion("JOB_CRONEXPRESSION <=", value, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionLike(String value) {
            addCriterion("JOB_CRONEXPRESSION like", value, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionNotLike(String value) {
            addCriterion("JOB_CRONEXPRESSION not like", value, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionIn(List<String> values) {
            addCriterion("JOB_CRONEXPRESSION in", values, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionNotIn(List<String> values) {
            addCriterion("JOB_CRONEXPRESSION not in", values, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionBetween(String value1, String value2) {
            addCriterion("JOB_CRONEXPRESSION between", value1, value2, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobCronexpressionNotBetween(String value1, String value2) {
            addCriterion("JOB_CRONEXPRESSION not between", value1, value2, "jobCronexpression");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIsNull() {
            addCriterion("JOB_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIsNotNull() {
            addCriterion("JOB_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionEqualTo(String value) {
            addCriterion("JOB_DESCRIPTION =", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotEqualTo(String value) {
            addCriterion("JOB_DESCRIPTION <>", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionGreaterThan(String value) {
            addCriterion("JOB_DESCRIPTION >", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_DESCRIPTION >=", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLessThan(String value) {
            addCriterion("JOB_DESCRIPTION <", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLessThanOrEqualTo(String value) {
            addCriterion("JOB_DESCRIPTION <=", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLike(String value) {
            addCriterion("JOB_DESCRIPTION like", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotLike(String value) {
            addCriterion("JOB_DESCRIPTION not like", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIn(List<String> values) {
            addCriterion("JOB_DESCRIPTION in", values, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotIn(List<String> values) {
            addCriterion("JOB_DESCRIPTION not in", values, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionBetween(String value1, String value2) {
            addCriterion("JOB_DESCRIPTION between", value1, value2, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotBetween(String value1, String value2) {
            addCriterion("JOB_DESCRIPTION not between", value1, value2, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeIsNull() {
            addCriterion("BUINESS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeIsNotNull() {
            addCriterion("BUINESS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeEqualTo(String value) {
            addCriterion("BUINESS_TYPE =", value, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeNotEqualTo(String value) {
            addCriterion("BUINESS_TYPE <>", value, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeGreaterThan(String value) {
            addCriterion("BUINESS_TYPE >", value, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BUINESS_TYPE >=", value, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeLessThan(String value) {
            addCriterion("BUINESS_TYPE <", value, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeLessThanOrEqualTo(String value) {
            addCriterion("BUINESS_TYPE <=", value, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeLike(String value) {
            addCriterion("BUINESS_TYPE like", value, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeNotLike(String value) {
            addCriterion("BUINESS_TYPE not like", value, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeIn(List<String> values) {
            addCriterion("BUINESS_TYPE in", values, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeNotIn(List<String> values) {
            addCriterion("BUINESS_TYPE not in", values, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeBetween(String value1, String value2) {
            addCriterion("BUINESS_TYPE between", value1, value2, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessTypeNotBetween(String value1, String value2) {
            addCriterion("BUINESS_TYPE not between", value1, value2, "buinessType");
            return (Criteria) this;
        }

        public Criteria andBuinessIdIsNull() {
            addCriterion("BUINESS_ID is null");
            return (Criteria) this;
        }

        public Criteria andBuinessIdIsNotNull() {
            addCriterion("BUINESS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBuinessIdEqualTo(Long value) {
            addCriterion("BUINESS_ID =", value, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdNotEqualTo(Long value) {
            addCriterion("BUINESS_ID <>", value, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdGreaterThan(Long value) {
            addCriterion("BUINESS_ID >", value, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdGreaterThanOrEqualTo(Long value) {
            addCriterion("BUINESS_ID >=", value, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdLessThan(Long value) {
            addCriterion("BUINESS_ID <", value, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdLessThanOrEqualTo(Long value) {
            addCriterion("BUINESS_ID <=", value, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdIn(List<Long> values) {
            addCriterion("BUINESS_ID in", values, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdNotIn(List<Long> values) {
            addCriterion("BUINESS_ID not in", values, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdBetween(Long value1, Long value2) {
            addCriterion("BUINESS_ID between", value1, value2, "buinessId");
            return (Criteria) this;
        }

        public Criteria andBuinessIdNotBetween(Long value1, Long value2) {
            addCriterion("BUINESS_ID not between", value1, value2, "buinessId");
            return (Criteria) this;
        }

        public Criteria andJobStatusIsNull() {
            addCriterion("JOB_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andJobStatusIsNotNull() {
            addCriterion("JOB_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andJobStatusEqualTo(String value) {
            addCriterion("JOB_STATUS =", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotEqualTo(String value) {
            addCriterion("JOB_STATUS <>", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusGreaterThan(String value) {
            addCriterion("JOB_STATUS >", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_STATUS >=", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLessThan(String value) {
            addCriterion("JOB_STATUS <", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLessThanOrEqualTo(String value) {
            addCriterion("JOB_STATUS <=", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusLike(String value) {
            addCriterion("JOB_STATUS like", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotLike(String value) {
            addCriterion("JOB_STATUS not like", value, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusIn(List<String> values) {
            addCriterion("JOB_STATUS in", values, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotIn(List<String> values) {
            addCriterion("JOB_STATUS not in", values, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusBetween(String value1, String value2) {
            addCriterion("JOB_STATUS between", value1, value2, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andJobStatusNotBetween(String value1, String value2) {
            addCriterion("JOB_STATUS not between", value1, value2, "jobStatus");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Long value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Long value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Long value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Long> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Long> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeIsNull() {
            addCriterion("CREATE_USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeIsNotNull() {
            addCriterion("CREATE_USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeEqualTo(String value) {
            addCriterion("CREATE_USER_TYPE =", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeNotEqualTo(String value) {
            addCriterion("CREATE_USER_TYPE <>", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeGreaterThan(String value) {
            addCriterion("CREATE_USER_TYPE >", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_TYPE >=", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeLessThan(String value) {
            addCriterion("CREATE_USER_TYPE <", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_TYPE <=", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeLike(String value) {
            addCriterion("CREATE_USER_TYPE like", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeNotLike(String value) {
            addCriterion("CREATE_USER_TYPE not like", value, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeIn(List<String> values) {
            addCriterion("CREATE_USER_TYPE in", values, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeNotIn(List<String> values) {
            addCriterion("CREATE_USER_TYPE not in", values, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeBetween(String value1, String value2) {
            addCriterion("CREATE_USER_TYPE between", value1, value2, "createUserType");
            return (Criteria) this;
        }

        public Criteria andCreateUserTypeNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_TYPE not between", value1, value2, "createUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(Long value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(Long value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(Long value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(Long value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(Long value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<Long> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<Long> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(Long value1, Long value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(Long value1, Long value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Long value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Long value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Long value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Long value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Long value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Long> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Long> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Long value1, Long value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Long value1, Long value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeIsNull() {
            addCriterion("UPDATE_USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeIsNotNull() {
            addCriterion("UPDATE_USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeEqualTo(String value) {
            addCriterion("UPDATE_USER_TYPE =", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeNotEqualTo(String value) {
            addCriterion("UPDATE_USER_TYPE <>", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeGreaterThan(String value) {
            addCriterion("UPDATE_USER_TYPE >", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_TYPE >=", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeLessThan(String value) {
            addCriterion("UPDATE_USER_TYPE <", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_TYPE <=", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeLike(String value) {
            addCriterion("UPDATE_USER_TYPE like", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeNotLike(String value) {
            addCriterion("UPDATE_USER_TYPE not like", value, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeIn(List<String> values) {
            addCriterion("UPDATE_USER_TYPE in", values, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeNotIn(List<String> values) {
            addCriterion("UPDATE_USER_TYPE not in", values, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_TYPE between", value1, value2, "updateUserType");
            return (Criteria) this;
        }

        public Criteria andUpdateUserTypeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_TYPE not between", value1, value2, "updateUserType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_job_message
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table device_job_message
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}